fixed CVE issues reported by sonatype ossindex audit
exasol/parquet-io-java pull request #41
Opened 2022-06-07 08:08 UTC by pj-spoelders

2022-06-07 16:19 UTC, tomuben commented on doc/changes/changes_1.3.1.md
> +Dependency updates
I remember asked us to use more specific names for the release summary. Maybe better:
```suggestion
Compile dependency updates for guava, hadoop-client and parquet-hadoop, along with updates for test and plugin packages.
```

2022-06-07 16:20 UTC, tomuben reviewed
Please check my comment.

2022-06-08 05:01 UTC, kaklakariada requested changes
Also replace `release_config.yml` with this new content:

```yml
release-platforms:
  - GitHub
  - Maven
  - Jira
```

2022-06-08 05:01 UTC, kaklakariada commented on doc/changes/changes_1.3.1.md
> +# Parquet for Java 1.3.1, released 2022-06-07
```suggestion
# Parquet for Java 1.3.1, released 2022-06-08
```

2022-06-09 12:12 UTC, kaklakariada commented
@pj-spoelders : I overlooked that you already made this PR and created #43. Sorry ☹️

2022-06-09 12:12 UTC, closed without merging